baseURL = "http://ronggle.com/"
languageCode = "en-us"
title = "凉都小道"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 2
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[params]
    since = 2015
    author = "Soi"                           # Author's name
    avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "道生一，一生二，二生三，三生万物"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""

    description = "Search Engine Oriented Programming."
    keywords = "Soi,Programming,Blog,ycrxun"

    beian = "黔ICP备15015267号"
    baiduAnalytics = "VNkd8ZiQJH29dqsu"

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.gitalk]
    clientId = "a2f917f5cb45d6dffe92"
    clientSecret = "879169dfceea28b064c49ef7fd190cdafcc6e5a7"
    repo = "ycrxun.github.io"
    owner = "ycrxun"
    admin = "ycrxun"
    distractionFreeMode = false

[params.social]
    GitHub = "ycrxun"
    Twitter = "ChangrongYang"
    #Email   = "ycrxun@163.com"
    #Instagram = "xxoo"
    Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    #Facebook = "xxoo"
    #Telegram = "xxoo"
    #Dribbble = "xxoo"
    #Medium = "xxoo"
